### PR TITLE
Tc001 altay ozyavas

### PR DESCRIPTION
**Pull request by altayozyavas**
Please review and merge my codes

### CODE REVIEW

**Comment by altayozyavas** [comment]
accept it please

**Comment by altayozyavas** [comment]
come on!!!

**Comment by altayozyavas** [comment]
I dont have time....

**Comment by TetP** [comment]
Looks good. Keep a good work

**Review by hasankayman — APPROVED** [review]

**Review by TetP — APPROVED** [review]

**Pull request merged**
